# This worflow notifies frenchyeti/dexcalibur-codedoc repository to generate doc and publish it 

name: CI

on:
  push:
    branches: [ master ]

jobs:
  notify_codedoc:
    runs-on: ubuntu-latest
    steps:
      - name: PING codedoc repository
        run: |
          curl -X POST https://api.github.com/repos/frenchyeti/dexcalibur-codedoc/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.CODEDOC_ACCESS_TOKEN }} \
          --data '{"event_type": "build-doc", "client_payload": {}}'
